In [25]:
import kagglehub
import os
import pandas as pd

path = kagglehub.dataset_download("nathansmallcalder/lol-match-history-and-summoner-data-80k-matches")

print(os.listdir(path))

champion = pd.read_csv(path + "/ChampionTbl.csv")
item = pd.read_csv(path + "/ItemTbl.csv")
matchstats = pd.read_csv(path + "/MatchStatsTbl.csv")
matchtbl = pd.read_csv(path + "/MatchTbl.csv")
ranking = pd.read_csv(path + "/RankTbl.csv")
summoner = pd.read_csv(path + "/SummonerMatchTbl.csv")
team = pd.read_csv(path + "/TeamMatchTbl.csv")

['ChampionTbl.csv', 'ItemTbl.csv', 'MatchStatsTbl.csv', 'MatchTbl.csv', 'RankTbl.csv', 'SummonerMatchTbl.csv', 'TeamMatchTbl.csv']

In [33]:
champion.columns

Index(['ChampionId', 'ChampionName'], dtype='str')

In [34]:
item.columns

Index(['ItemID', 'ItemName'], dtype='str')

In [35]:
matchstats.columns

Index(['MatchStatsId', 'SummonerMatchFk', 'MinionsKilled', 'DmgDealt',
       'DmgTaken', 'TurretDmgDealt', 'TotalGold', 'Lane', 'Win', 'item1',
       'item2', 'item3', 'item4', 'item5', 'item6', 'kills', 'deaths',
       'assists', 'PrimaryKeyStone', 'PrimarySlot1', 'PrimarySlot2',
       'PrimarySlot3', 'SecondarySlot1', 'SecondarySlot2', 'SummonerSpell1',
       'SummonerSpell2', 'CurrentMasteryPoints', 'EnemyChampionFk',
       'DragonKills', 'BaronKills', 'visionScore'],
      dtype='str')

In [36]:
matchtbl.columns

Index(['MatchId', 'Patch', 'QueueType', 'RankFk', 'GameDuration'], dtype='str')

In [37]:
ranking.columns

Index(['RankId', 'RankName'], dtype='str')

In [38]:
summoner.columns

Index(['SummonerMatchId', 'SummonerFk', 'MatchFk', 'ChampionFk'], dtype='str')

In [39]:
team.columns

Index(['TeamID', 'MatchFk', 'B1Champ', 'B2Champ', 'B3Champ', 'B4Champ',
       'B5Champ', 'R1Champ', 'R2Champ', 'R3Champ', 'R4Champ', 'R5Champ',
       'BlueBaronKills', 'BlueRiftHeraldKills', 'BlueDragonKills',
       'BlueTowerKills', 'BlueKills', 'RedBaronKills', 'RedRiftHeraldKills',
       'RedDragonKills', 'RedTowerKills', 'RedKills', 'RedWin', 'BlueWin'],
      dtype='str')

In [65]:
champ_enemy = champion.rename(columns={
    "ChampionId": "EnemyChampionFk",
    "ChampionName": "EnemyChampion"
})

champ_player = champion.rename(columns={
    "ChampionId": "ChampionFk",
    "ChampionName": "PlayerChampion"
})
item1 = item.rename(columns={"ItemID":"item1","ItemName" : "ItemSlot1"})
item2 = item.rename(columns={"ItemID":"item2","ItemName" : "ItemSlot2"})
item3 = item.rename(columns={"ItemID":"item3","ItemName" : "ItemSlot3"})
item4 = item.rename(columns={"ItemID":"item4","ItemName" : "ItemSlot4"})
item5 = item.rename(columns={"ItemID":"item5","ItemName" : "ItemSlot5"})
item6 = item.rename(columns={"ItemID":"item6","ItemName" : "ItemSlot6"})

In [64]:
item1.head(1)

,PlayerChampion,EnemyChampion,ItemSlot1,MinionsKilled,MatchStatsId,SummonerMatchFk,DmgDealt,DmgTaken,TurretDmgDealt,TotalGold,Lane,Win,item1,item2,item3,item4,item5,item6,kills,deaths,assists,PrimaryKeyStone,PrimarySlot1,PrimarySlot2,PrimarySlot3,SecondarySlot1,SecondarySlot2,SummonerSpell1,SummonerSpell2,CurrentMasteryPoints,EnemyChampionFk,DragonKills,BaronKills,visionScore,SummonerMatchId,SummonerFk,MatchFk,ChampionFk,item1
0,Milio,Caitlyn,Dream Maker,30,1,1,4765,12541,0,7058,BOTTOM,0,3870,2055,3107,3171,6620,2022,0,2,12,8465,8463,8473,8453,8345,8347,4,7,902,51,0,0,67,1.0,1.0,EUW1_7565751492,902.0,3870.0

In [72]:
partida = (
    matchstats
    .merge(champ_enemy, on="EnemyChampionFk", how="left")
    .merge(summoner, left_on="SummonerMatchFk", right_on="SummonerMatchId", how="left")
    .merge(champ_player, on="ChampionFk", how="left")
    .merge(item1, on = "item1", how="left")
    .merge(item2, on = "item2", how="left")
    .merge(item3, on = "item3", how="left")
    .merge(item4, on = "item4", how="left")
    .merge(item5, on = "item5", how="left")
    .merge(item6, on = "item6", how="left")
    .merge(matchtbl, left_on="MatchFk", right_on="MatchId", how="left")
)

cols = ["PlayerChampion", "EnemyChampion","ItemSlot1","ItemSlot2","ItemSlot3","ItemSlot4","ItemSlot5","ItemSlot6","QueueType","MinionsKilled"] + [
    c for c in partida.columns if c not in ["QueueType","ItemSlot1","ItemSlot2","ItemSlot3","ItemSlot4","ItemSlot5","ItemSlot6","MinionsKilled", "PlayerChampion", "EnemyChampion"]
]


partida = partida[cols]

partida.head(10)

,PlayerChampion,EnemyChampion,ItemSlot1,ItemSlot2,ItemSlot3,ItemSlot4,ItemSlot5,ItemSlot6,QueueType,MinionsKilled,MatchStatsId,SummonerMatchFk,DmgDealt,DmgTaken,TurretDmgDealt,TotalGold,Lane,Win,item1,item2,item3,item4,item5,item6,kills,deaths,assists,PrimaryKeyStone,PrimarySlot1,PrimarySlot2,PrimarySlot3,SecondarySlot1,SecondarySlot2,SummonerSpell1,SummonerSpell2,CurrentMasteryPoints,EnemyChampionFk,DragonKills,BaronKills,visionScore,SummonerMatchId,SummonerFk,MatchFk,ChampionFk,MatchId,Patch,RankFk,GameDuration
0,Milio,Caitlyn,Dream Maker,Control Ward,Redemption,Crimson Lucidity,Echoes of Helia,Glowing Mote,CLASSIC,30,1,1,4765,12541,0,7058,BOTTOM,0,3870,2055,3107,3171,6620,2022,0,2,12,8465,8463,8473,8453,8345,8347,4,7,902,51,0,0,67,1.0,1.0,EUW1_7565751492,902.0,EUW1_7565751492,15.20.717.2831,7.0,1751.0
1,Milio,Lucian,Dream Maker,Shurelya's Battlesong,Redemption,Ionian Boots of Lucidity,Echoes of Helia,Oblivion Orb,CLASSIC,29,2,2,8821,14534,1,9618,BOTTOM,0,3870,2065,3107,3158,6620,3916,2,5,23,8465,8463,8473,8453,8345,8347,4,7,902,236,0,0,88,2.0,1.0,EUW1_7565549583,902.0,EUW1_7565549583,15.20.717.2831,7.0,2092.0
2,Soraka,Xayah,Dream Maker,Redemption,Giant's Belt,Crimson Lucidity,Moonstone Renewer,Oblivion Orb,CLASSIC,34,3,3,6410,19011,3,9877,BOTTOM,1,3870,3107,1011,3171,6617,3916,0,5,22,8214,8226,8210,8237,8345,8347,4,7,16,498,0,0,97,3.0,1.0,EUW1_7564803077,16.0,EUW1_7564803077,15.20.717.2831,7.0,2332.0
3,Ahri,Malphite,Luden's Companion,Rabadon's Deathcap,Shadowflame,Sorcerer's Shoes,NaN,NaN,ARAM,51,4,4,22206,14771,3,12374,NONE,1,6655,3089,4645,3020,0,0,8,4,35,8112,8143,8140,8106,8226,8210,4,14,103,54,0,0,0,4.0,1.0,EUW1_7564368646,103.0,EUW1_7564368646,15.20.717.2831,7.0,984.0
4,Mel,Alistar,Perplexity,Zhonya's Hourglass,Liandry's Anguish,Blackfire Torch,Rabadon's Deathcap,Runecarver,CHERRY,0,5,5,39106,33572,0,15012,TOP,1,4015,223157,226653,222503,223089,447108,13,8,2,0,0,0,0,0,0,2202,2201,800,12,0,0,0,5.0,1.0,EUW1_7564332041,800.0,EUW1_7564332041,15.20.717.2831,7.0,1541.0
5,Lissandra,Ornn,Guardian's Orb,Zhonya's Hourglass,Runecarver,Sorcerer's Shoes,Rabadon's Deathcap,Crown of the Shattered Queen,CHERRY,0,6,6,30259,21355,0,12000,TOP,1,223112,223157,447108,223020,223089,444644,6,6,4,0,0,0,0,0,0,2202,2201,127,516,0,0,0,6.0,1.0,EUW1_7564297394,127.0,EUW1_7564297394,15.20.717.2831,7.0,1648.0
6,Milio,Aphelios,Dream Maker,Control Ward,Echoes of Helia,Ionian Boots of Lucidity,Oblivion Orb,Kindlegem,CLASSIC,28,7,7,3775,12061,0,6344,BOTTOM,0,3870,2055,6620,3158,3916,3067,0,1,7,8214,8226,8210,8237,8345,8347,4,7,902,523,0,0,60,7.0,1.0,EUW1_7564257986,902.0,EUW1_7564257986,15.20.717.2831,7.0,1676.0
7,Nami,Ezreal,Dream Maker,Shurelya's Battlesong,NaN,Ionian Boots of Lucidity,Imperial Mandate,NaN,CLASSIC,36,8,8,4217,13464,0,7403,BOTTOM,0,3870,2065,0,3158,4005,0,1,5,6,8214,8226,8210,8237,8345,8347,4,7,267,81,0,0,55,8.0,1.0,EUW1_7563685543,267.0,EUW1_7563685543,15.20.717.2831,7.0,1749.0
8,Milio,Sivir,Dream Maker,Redemption,Shurelya's Battlesong,Ionian Boots of Lucidity,Echoes of Helia,Oblivion Orb,CLASSIC,31,9,9,10255,19432,1,11905,BOTTOM,1,3870,3107,2065,3158,6620,3916,2,2,30,8214,8226,8210,8237,8345,8347,4,7,902,15,0,0,83,9.0,1.0,EUW1_7563605642,902.0,EUW1_7563605642,15.20.717.2831,7.0,2313.0
9,Leblanc,Twitch,Luden's Companion,Zhonya's Hourglass,Sorcerer's Shoes,Stormsurge,Rabadon's Deathcap,Hextech Alternator,ARAM,42,10,10,51900,32851,2,18209,TOP,1,6655,3157,3020,4646,3089,3145,15,10,43,8112,8139,8140,8135,8014,9111,4,14,7,29,0,0,0,10.0,1.0,EUW1_7563553417,7.0,EUW1_7563553417,15.20.717.2831,7.0,1401.0